### ISSUE TITLE
Invalid formula in IE

### ISSUE THREAD

**Issue by nibinblessy** [projazzka/jazzy-forms-dev#102]
Hi,

I have created a calculator with jazzy. It is working fine in chrome and firefox. Bit in IE it is giving error "invalid formula"

http://magnumfuelrx.com/calculator/

CAn you please advise the solution?

thanks

**Comment by projazzka** [comment]
Hi. I've tried with IE9 on Win7 and IE6 on XP and I didn't see any problem. Could you provide more information on your environment, please?

**Comment by nibinblessy** [comment]
Im sorry. I think its an error with my PC. I just tried on other pc and found it is working. Thanks.
