### ISSUE TITLE
Creating second form deletes first

### ISSUE THREAD

**Issue by brookevmf** [projazzka/jazzy-forms-dev#112]
Hi, my colleague just spent 10 hours working on a form and tried to create a second one to do some tests, but when he did it deleted the first form. Since then we've tried creating more than one form and it hasn't worked. 

I'm not sure if this has been reported before, but it would be great to be able to create more than one form (and, sadly, retrieve his lost work).

Let me know if you have any tips for us!

**Comment by projazzka** [comment]
Sorry for getting back to you with such a delay. I've been busy with other stuff. Are you sure you are hitting the "Save" button before adding the second form? I guess so.

I'm working with multiple forms and have automized test cases in place for adding them from scratch. I haven't been able to reproduce you're problem.

Are you able to look into the database? A dump of the tables starting whose names start with wp_jzzf could give us a hint and might even help to recover your data.

**Comment by brookevmf** [comment]
Thanks for your response!  I updated my WP and that helped with the saving problem, so I'll close this issue. I do have another question about the functions though, so will post a new issue for that.
