### ISSUE TITLE
Invalid Formula When Form is Use In Other Locations

### ISSUE THREAD

**Issue by lisarae1** [projazzka/jazzy-forms-dev#113]
I am having an issue with the form I created generating Invalid Formula when used in the locations that I need it. 

The first location is my homeopage which uses a page builder to create the layout. The field which I have the shortcode states that it excepts shortcode: http://www.dieselfusion.com

I have also tried to add the form to a sidebar and get the same result. I have added the form to the main page so you can see it works in the page:  http://www.dieselfusion.com/company

What can I do to get the form to work on my homepage?

**Comment by projazzka** [comment]
Duplicated. See known issue #53.
Thank you lisarae1. My apologies for the 6 months of silence. This project has been frozen for almost a year.
