### ISSUE TITLE
Add Conditional (IF/THEN) Statements

### ISSUE THREAD

**Issue by amyreitz** [projazzka/jazzy-forms-dev#28]
I'd like to be able to use if/then/else statements within the output formulas.  It would be especially useful if statements could be nested.  For example,

IF a < 10 THEN a \* 2 ELSE IF a > 20 THEN a \* 3 ELSE a \* 2.5

In this case, if a is less than 10, it is multiplied by 2 - if a is between 10 and 20 it is multiplied by 2.5 - and if a is greater than 20 it is multiplied by 3.

I would like to use this to do a basic income tax calculation, but it is difficult to account for the marginal tax brackets without conditional statements.

Thanks!

**Comment by projazzka** [comment]
Hi amyreitz, an IF clause is already there in v0.9.2. There is no documentation whatsoever, so your confusion was preprogrammed. Sorry for that. The correct notation for Jazzy Form is:

`IF(a<10, a*2, IF(a>20, a*3, a*2.5))`

Or more generally spoken:
`IF(condition, value_if_true, value_if_false)`

I've set up a demo page at http://mundoacustico.com/sandbox/wp1/?p=31

**Comment by projazzka** [comment]
(Marked as duplicate of fixed issue https://github.com/l90r/jazzy-forms-dev/issues/10)

**Comment by amyreitz** [comment]
I don't know why I didn't just try using excel notation to begin with.  Works great.  Thank you!
