### ISSUE TITLE
Headers and text disappear with native IE8

### ISSUE THREAD

**Issue by projazzka** [projazzka/jazzy-forms-dev#46]
Reported by "Henry" and available online at  http://www.edc-ecrf.com/strumenti/mini-mental-state-examination-test-calcolo-punteggio-mmse/

Note: IE8 mode in IE9 does not reproduce the problem.

**Comment by pashast** [comment]
file tmpl-list.php, 57

`<div class="<?php echo $element->classes ?>"  "<?php if($element->visible===0): ?> style="display:none;"<?php endif ?>>`

replace with

`<div class="<?php echo $element->classes ?>" <?php if($element->visible===0): ?> style="display:none;"<?php endif ?> >`

**Comment by projazzka** [comment]
Thank you very much, pashast! Committed as 17e9d9fbfd5269ceb57ae8a2f84224e2f08d7122 (will be available in next update v0.9.6)
