### ISSUE TITLE
Email: numeric fields cause Javascript error

### ISSUE THREAD

**Issue by projazzka** [projazzka/jazzy-forms-dev#63]
If an input field is passed directly to a email placeholder (for example a telephone number), then a Javascript error prevents the email from being sent.

"Uncaught TypeError: Cannot read property 'decimals' of undefined"
jazzy-forms.js:419

**Comment by Neo2SHYAlien** [comment]
Temporal fix is stop formatting numeric data in line 129 
<code>val = jzzf_format(val, graph.params[id]); </code> 
and replace it with 
<code> val=val; </code>
The problem is graph.params[id] doesn’t have value. I don't have more time for debugging to provide you fix for it

**Comment by projazzka** [comment]
Thank you very much! Indeed, the error consists in trying to do number formatting on input fields that don't have any formatting settings associated with them. Commit ac10ad13270057d2251f48c81b4b482d279ee36e
