### ISSUE TITLE
multi site issue

### ISSUE THREAD

**Issue by Neo2SHYAlien** [projazzka/jazzy-forms-dev#65]
I found multi site issue in version 0.9.7 . When creating new network site plugin can't save the new form and elements for it. This is because the plugin can't create new tables for the new network site. The solution is really simple - in file <b>jazzy-forms.php</b> in function <b>jzzf_update</b> change row 136  
<code>jzzf_execute_sql(JZZF_GENERATED . 'update.sql'); </code>
with this
<code>
if (function_exists('is_multisite') && is_multisite()) jzzf_execute_sql(JZZF_GENERATED . 'schema.sql');
else jzzf_execute_sql(JZZF_GENERATED . 'update.sql');
</code>
it's not the best way to do this but it wors perfectly for me :)

**Comment by projazzka** [comment]
Hey, thanks for pointing that out! Evidently I haven't taken multi-site scenarios into account. We are talking about WPMU, right? Yeah, as far as I remember WPMU creates a set of tables with a new prefix. Your patch seems quite unobtrusive for non-multisite installations, I'll give it a try. Thank you!

**Comment by projazzka** [comment]
Commit 6d631a008612fd9f69fbdbebe5c93d755542174d
