### ISSUE TITLE
Emails not sending.

### ISSUE THREAD

**Issue by benyafai** [projazzka/jazzy-forms-dev#68]
After form data is entered, I press the email button and get presented with the 'sending' text, but it seems to stop and email does not send.

In chrome, inspector shows error on line 393:

Uncaught TypeError: Cannot read property 'decimals' of undefined 

Using version 0.9.7

**Comment by Neo2SHYAlien** [comment]
This issues with numeric fields https://github.com/l90r/jazzy-forms-dev/issues/63 . I post temporary fix for it. Author commit fix too.

**Comment by benyafai** [comment]
Thanks!
