### ISSUE TITLE
Email hangs on sending

### ISSUE THREAD

**Issue by loverv** [projazzka/jazzy-forms-dev#79]
Hi

I've tried installing this plugin and set it up.

It just hangs on sending email.

Everything seems to be set up correctly.

**Comment by projazzka** [comment]
Thanks for the report, loverv. What exactly do you mean by "it hangs"? I would like you to be more specific. Do you see the "Sending..." next to the send button? Are you able to detect with your browser whether there are Javascript errors?

**Comment by loverv** [comment]
hi sorry for the delay in getting back to you.

It hangs and doesn't change at all., there is no, sending message when viewing from a google Chrome browser but there is from an ipad, this doesn't change to a sent or error message, just sending.

I have checked on google chrome the error that is displayed when email is clicked, this is it:

Uncaught TypeError: Object #<Object> has no method 'parentsUntil' jazzy-forms.js:89
set_message jazzy-forms.js:89
send_email jazzy-forms.js:97
just_updated jazzy-forms.js:52
o.event.handle jquery.js:19
o.event.add.J jquery.js:19

It may be something that i'm doing incorrectly, if so please let me know what.

**Comment by projazzka** [comment]
Oh, apparently you are using an outdated jQuery library on your page (prior to 1.4). Jazzy Forms tries to queue the latest one for inclusion, but your theme or another plugin might have overridden that in some way -- maybe forcing an own copy of jQuery to be loaded. Could you check that?

**Comment by loverv** [comment]
I had some other script using jquery that was stopping something, anyway i removed that and checked the errors again and i'm getting this:

Uncaught TypeError: Cannot read property '0' of undefined jazzy-forms.js:233
evaluate_formula jazzy-forms.js:233
send_email jazzy-forms.js:100
just_updated jazzy-forms.js:52
c.event.handle jquery.min.js:54
c.event.add.j jquery.min.js:49

the jquery version is 1.4.1

**Comment by seismo** [comment]
Hi Jazzy, 
I've got the same or similar problem. E-mail won't send on clicking sending button (Message "Sending" appears but then nothing happens) 
I Checked following issues: 
- we are using the responsive WP-template AWARE http://themewich.com/themes/?theme=Aware(Responsive) and it seems that it collides with this template
- checked it with the twentyeleven template and it works fine
- the jquery version is 1.4.4

The link to our test form is:
http://www.franzjosephs.at/kuk/?page_id=294

Your plugin is great and the only thing which could work with our order form. 
Please let us know if you have an idea what could cause this problem. 

Really appreciate your answer
Oliver

**Comment by projazzka** [comment]
Hi guys, this response comes kind of late, I know. Please accept my apologies, I'm doing this as a side-project, currently without any monetary return.

loverv, I hadn't had the chance to look closer into your case. However, meanwhile much of the code that seems to have caused your trouble has changed fundamentally. So with a bit of luck it might be fixed as a side-effect.

"seismo", what you are describing (getting stuck in "Sending...") is identical to an issue that has been fixed in v0.10.1. I hope an update will do.

Closing this until new evidence is available.
